# Generated by Django 4.1.7 on 2023-04-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
