# Generated by Django 4.1.7 on 2023-04-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0002_rename_nombre_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(default='', max_length=50),
        ),
    ]
